#Yolo Model settings
import cv2

MODEL_PATH = "models/TestModel.pt"
IMAGE_SIZE = 640

#image settings 
BOX_THICKNESS = 2
FONT_SCALE = 0.6
TEXT_THICKNESS = 2
TEXT_STYLE = cv2.FONT_HERSHEY_SIMPLEX

# Confidence settings
CONFIDENCE = 0.5
LOW_CONFIDENCE= 0.5
MEDIUM_CONFIDENCE = 0.8

#stabilization of model 
STABILIZATION_FRAMES = 5
STABILIZATION_THRESHOLD = 0.6